### ISSUE TITLE
Solve() has asymmetric abilities for sin vs cos

### ISSUE THREAD

**Issue by thunderkid** [geogebra/giac#7]
The `solve` algorithm seems to have an asymmetry in its trigonometric abilities. To solve a right-angle triangle with base `3` and height `L`:
`solve([x = r*cos(t), y=r*sin(t), x=3, y=L], [x, y, r, t])`
gives the correct solution.

But to solve the same triangle with base and height flipped:
`solve([x = r*cos(t), y=r*sin(t), x=L, y=3], [x, y, r, t])`
gives `[]`. i.e. it finds no solutions.

**Comment by parisseb** [comment]
At some point during the solving process, the system is reduced to find r such that 
[r*cos(1/2*(pi*sign(L)-2*atan(3/L)-pi))-L,-r*sin(1/2*(pi*sign(L)-2*atan(3/L)-pi))-3]=[0,0]
Then one equation is solved and the value of r is substitued in the second equation. But checking fails because full simplification with sign(L) fail.
If you run assume(L>0), sign(L) will be replaced by 1, the simplification will work and the solution is returned.
